...

diff --git a/install b/install
--- a/install
+++ b/install
@@ -57,13 +57,13 @@ fi
 
 # needed packages
 needed_pacman_packages=(
-  "lshw" "bluez" "bluez-utils" "brightnessctl" "file-roller" "grim" "imagemagick"
+  "hyprland" "nano" "lshw" "bluez" "bluez-utils" "brightnessctl" "file-roller" "grim" "imagemagick"
   "gvfs" "inotify-tools" "libinput" "lm_sensors" "pavucontrol" "python-pam" "slurp" "swayidle"
   "wl-clipboard" "tracker3" "tracker3-miners" "qt5-base" "qt6-base" "gnome-bluetooth" "gnome-control-center"
 )
 
 needed_aur_packages=(
-  "aylurs-gtk-shell-git" "grimblast-git" "gtklock" "gtklock-userinfo-module" "hyprland-git"
+  "aylurs-gtk-shell-git" "grimblast-git" "gtklock" "gtklock-userinfo-module" 
   "hyprpicker" "libadwaita-without-adwaita-git" "ttf-ubuntu-nerd" "ttf-ubuntu-mono-nerd"
   "sway-audio-idle-inhibit-git" "swww-git" "pywal-16-colors" "xdg-desktop-portal-hyprland"
   "wf-recorder" "wl-clip-persist-git"
@@ -194,6 +194,21 @@ else
     mkdir -p ~/.themes
     echo "~/.themes was created!"
     cp -r ./hyprland-gtk-themes/* ~/.themes
+  fi
+fi
+
+# install git version of Hyprland
+read -p "Do you want to install the Git-Version of Hyprland? (Y/n): " choice
+
+if [[ $choice == "n" || $choice == "N" ]]; then
+  echo "hyprland-git was not installed!"
+else
+  echo "installing 'hyprland-git' ..."
+  yay -S hyprland-git
+  if [ $? -eq 0 ]; then
+    echo "hyprland-git was installed!"
+  else
+    echo "Installation was aborted! Make sure you have 'yay' installed! "
   fi
 fi
 
