...

diff --git a/installers/install b/installers/install
--- a/installers/install
+++ b/installers/install
@@ -58,13 +58,13 @@ fi
 # needed packages
 needed_pacman_packages=(
   "hyprland" "nano" "lshw" "wezterm" "bluez" "bluez-utils" "brightnessctl" "file-roller" "grim" "imagemagick"
-  "gvfs" "inotify-tools" "libinput" "lm_sensors" "pavucontrol" "python-pam" "slurp" "swayidle"
+  "gvfs" "inotify-tools" "libinput" "lm_sensors" "pavucontrol" "python-pam" "slurp" "swayidle" "playerctl"
   "wl-clipboard" "tracker3" "tracker3-miners" "qt5-base" "qt6-base" "gnome-bluetooth" "gnome-control-center"
 )
 
 needed_aur_packages=(
   "aylurs-gtk-shell-git" "grimblast-git" "gtklock" "gtklock-userinfo-module" 
-  "hyprpicker" "libadwaita-without-adwaita-git" "ttf-ubuntu-nerd" "ttf-ubuntu-mono-nerd"
+  "hyprpicker" "ttf-ubuntu-nerd" "ttf-ubuntu-mono-nerd"
   "sway-audio-idle-inhibit-git" "swww-git" "pywal-16-colors" "xdg-desktop-portal-hyprland"
   "wf-recorder" "wl-clip-persist-git"
 )
@@ -207,6 +207,21 @@ else
   yay -S hyprland-git
   if [ $? -eq 0 ]; then
     echo "hyprland-git was installed!"
+  else
+    echo "Installation was aborted! Make sure you have 'yay' installed! "
+  fi
+fi
+
+# install libadwaita-without-adwaita-git
+read -p "Install libadwaita-without-adwaita? This is needed to run GTK4/Adwaita applications with a GTK3 theme... (Y/n): " choice
+
+if [[ $choice == "n" || $choice == "N" ]]; then
+  echo "libadwaita-without-adwaita-git was not installed!"
+else
+  echo "installing 'libadwaita-without-adwaita-git' ..."
+  yay -S libadwaita-without-adwaita-git
+  if [ $? -eq 0 ]; then
+    echo "libadwaita-without-adwaita-git was installed!"
   else
     echo "Installation was aborted! Make sure you have 'yay' installed! "
   fi
